2021-08-05 00:25:35.601 CST [9636] LOG:  starting PostgreSQL 12.4, compiled by Visual C++ build 1914, 64-bit
2021-08-05 00:25:35.612 CST [9636] LOG:  listening on IPv6 address "::1", port 5432
2021-08-05 00:25:35.613 CST [9636] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-08-05 00:25:35.723 CST [4764] LOG:  database system was shut down at 2021-08-05 00:25:26 CST
2021-08-05 00:25:35.780 CST [9636] LOG:  database system is ready to accept connections
2021-08-05 00:32:55.069 CST [12064] ERROR:  relation "public.untitled_table_218" does not exist at character 15
2021-08-05 00:32:55.069 CST [12064] STATEMENT:  SELECT * FROM "public"."untitled_table_218" LIMIT 1 OFFSET 0;
2021-08-05 00:32:55.085 CST [12064] ERROR:  invalid input syntax for type oid: "" at character 1445
2021-08-05 00:32:55.085 CST [12064] STATEMENT:  SELECT c.conname AS constraint_name,tf.schema AS child_schema,tf.name AS child_name,(SELECT STRING_AGG(QUOTE_IDENT(a.attname),','ORDER BY t.seq)FROM(SELECT ROW_NUMBER()OVER(ROWS UNBOUNDED PRECEDING)AS seq,attnum FROM UNNEST(c.conkey)AS t(attnum))AS t INNER JOIN pg_attribute AS a ON a.attrelid=c.conrelid AND a.attnum=t.attnum)AS child_column,tt.schema as parent_schema,tt.name AS parent_name,(SELECT STRING_AGG(QUOTE_IDENT(a.attname),','ORDER BY t.seq)FROM(SELECT ROW_NUMBER()OVER(ROWS UNBOUNDED PRECEDING)AS seq,attnum FROM UNNEST(c.confkey)AS t(attnum))AS t INNER JOIN pg_attribute AS a ON a.attrelid=c.confrelid AND a.attnum=t.attnum)AS parent_column,CASE confupdtype WHEN'r'THEN'restrict'WHEN'c'THEN'cascade'WHEN'n'THEN'set null'WHEN'd'THEN'set default'WHEN'a'THEN'no action'ELSE NULL END AS on_update,CASE confdeltype WHEN'r'THEN'restrict'WHEN'c'THEN'cascade'WHEN'n'THEN'set null'WHEN'd'THEN'set default'WHEN'a'THEN'no action'ELSE NULL END AS on_delete FROM pg_catalog.pg_constraint AS c INNER JOIN(SELECT pg_class.oid,QUOTE_IDENT(pg_namespace.nspname)as schema,QUOTE_IDENT(pg_class.relname)AS name FROM pg_class INNER JOIN pg_namespace ON pg_class.relnamespace=pg_namespace.oid)AS tf ON tf.oid=c.conrelid INNER JOIN(SELECT pg_class.oid,QUOTE_IDENT(pg_namespace.nspname)as schema,QUOTE_IDENT(pg_class.relname)AS name FROM pg_class INNER JOIN pg_namespace ON pg_class.relnamespace=pg_namespace.oid)AS tt ON tt.oid=c.confrelid WHERE tf.oid='' AND c.contype='f';
2021-08-05 00:39:16.511 CST [12064] ERROR:  duplicate key value violates unique constraint "yfcase_city_pkey"
2021-08-05 00:39:16.511 CST [12064] DETAIL:  Key (id)=(1) already exists.
2021-08-05 00:39:16.511 CST [12064] STATEMENT:  INSERT INTO "public"."yfcase_city" ("id", "name") VALUES
	(1, '台南');
2021-08-05 00:39:36.035 CST [12064] ERROR:  duplicate key value violates unique constraint "yfcase_city_pkey"
2021-08-05 00:39:36.035 CST [12064] DETAIL:  Key (id)=(1) already exists.
2021-08-05 00:39:36.035 CST [12064] STATEMENT:  INSERT INTO "public"."yfcase_city" ("name") VALUES
	('台南');
2021-08-05 07:24:35.906 CST [9636] LOG:  server process (PID 11040) was terminated by exception 0xC000013A
2021-08-05 07:24:35.906 CST [9636] DETAIL:  Failed process was running: /*pga4dash*/
	SELECT 'session_stats' AS chart_name, row_to_json(t) AS chart_data
	FROM (SELECT
	   (SELECT count(*) FROM pg_stat_activity WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16387)) AS "Total",
	   (SELECT count(*) FROM pg_stat_activity WHERE state = 'active' AND datname = (SELECT datname FROM pg_database WHERE oid = 16387))  AS "Active",
	   (SELECT count(*) FROM pg_stat_activity WHERE state = 'idle' AND datname = (SELECT datname FROM pg_database WHERE oid = 16387))  AS "Idle"
	) t
	UNION ALL
	SELECT 'tps_stats' AS chart_name, row_to_json(t) AS chart_data
	FROM (SELECT
	   (SELECT sum(xact_commit) + sum(xact_rollback) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16387)) AS "Transactions",
	   (SELECT sum(xact_commit) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16387)) AS "Commits",
	   (SELECT sum(xact_rollback) FROM pg_stat_database WHERE datname = (SELECT datname FROM pg_database WHERE oid = 16387)) AS "Rollbacks"
	) 
2021-08-05 07:24:35.906 CST [9636] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2021-08-05 07:24:35.907 CST [9636] LOG:  terminating any other active server processes
2021-08-05 07:24:35.932 CST [14184] WARNING:  terminating connection because of crash of another server process
2021-08-05 07:24:35.932 CST [14184] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-08-05 07:24:35.932 CST [14184] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-08-05 07:24:35.957 CST [9636] LOG:  all server processes terminated; reinitializing
2021-08-05 07:24:36.063 CST [14568] LOG:  database system was interrupted; last known up at 2021-08-05 07:22:43 CST
2021-08-05 07:24:36.534 CST [14568] LOG:  database system was not properly shut down; automatic recovery in progress
2021-08-05 07:24:36.541 CST [14568] LOG:  redo starts at 0/1756D60
2021-08-05 07:24:36.542 CST [14568] LOG:  invalid record length at 0/1756E48: wanted 24, got 0
2021-08-05 07:24:36.542 CST [14568] LOG:  redo done at 0/1756E10
2021-08-05 07:24:36.619 CST [9636] LOG:  database system is ready to accept connections
2021-08-05 07:24:48.016 CST [13552] ERROR:  canceling statement due to user request
2021-08-05 07:24:48.031 CST [8380] ERROR:  canceling statement due to user request
2021-08-05 07:24:48.045 CST [9636] LOG:  received fast shutdown request
2021-08-05 07:24:48.053 CST [9636] LOG:  aborting any active transactions
2021-08-05 07:24:48.056 CST [9636] LOG:  background worker "logical replication launcher" (PID 13552) exited with exit code 1
2021-08-05 07:24:48.092 CST [10860] LOG:  shutting down
2021-08-05 07:24:48.150 CST [9636] LOG:  database system is shut down
